#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 [e/edit | u/update | p/push]"
    exit 1
fi

case "$1" in
    e|edit)
        nvim "../flake.nix"
        ;;
    u|update)
        nix flake update "../."
        darwin-rebuild switch --flake "../."
        ;;
    p|push)
        REV = $(jq -r '.nodes.nixpkgs.locked.rev' "../flake.lock")
        git add -A
        git commit -m "Update nixpkgs to $REV"
        git push
        ;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 [e/edit | u/update | p/push]"
        exit 1
        ;;
esac
